In [1]:
import pandas as pd
import numpy as np
import joblib

In [2]:
df = pd.read_csv("customer.csv")
df.head()

,Age,AnnualIncome,NumberOfPurchases,TimeSpentOnWebsite,CustomerTenureYears,LastPurchaseDaysAgo,Gender,ProductCategory,PreferredDevice,Region,ReferralSource,CustomerSegment,LoyaltyProgram,DiscountsAvailed,SessionCount,CustomerSatisfaction,PurchaseStatus,SpendingScore
0,37,57722.57241,19,5.908826,1.093430,11,Male,Furniture,Desktop,South,Paid Ads,Regular,1,5,3,2,1,86.0
1,63,21328.92588,10,6.970749,0.649246,20,Female,Furniture,Mobile,East,Organic,VIP,0,4,2,3,0,37.0
2,60,150537.74250,19,35.004954,3.858211,25,Male,Electronics,Desktop,South,Organic,VIP,1,2,5,2,0,86.0
3,19,63508.76255,10,14.818000,7.554374,20,Male,Furniture,Desktop,West,Paid Ads,Premium,0,0,1,3,0,37.0
4,54,100399.55840,19,55.925462,0.197411,92,Male,Electronics,Mobile,South,Referral,Regular,1,4,1,2,0,86.0

In [3]:
df.isnull().sum()

Age                       0
AnnualIncome              0
NumberOfPurchases         0
TimeSpentOnWebsite        0
CustomerTenureYears       0
LastPurchaseDaysAgo       0
Gender                    0
ProductCategory           0
PreferredDevice           0
Region                    0
ReferralSource            0
CustomerSegment           0
LoyaltyProgram            0
DiscountsAvailed          0
SessionCount              0
CustomerSatisfaction      0
PurchaseStatus            0
SpendingScore           540
dtype: int64

In [4]:
import math
median_SpendingScore = math.floor(df.SpendingScore.median())
median_SpendingScore

47

In [5]:
df.SpendingScore = df.SpendingScore.fillna(median_SpendingScore)
df

,Age,AnnualIncome,NumberOfPurchases,TimeSpentOnWebsite,CustomerTenureYears,LastPurchaseDaysAgo,Gender,ProductCategory,PreferredDevice,Region,ReferralSource,CustomerSegment,LoyaltyProgram,DiscountsAvailed,SessionCount,CustomerSatisfaction,PurchaseStatus,SpendingScore
0,37,57722.57241,19,5.908826,1.093430,11,Male,Furniture,Desktop,South,Paid Ads,Regular,1,5,3,2,1,86.0
1,63,21328.92588,10,6.970749,0.649246,20,Female,Furniture,Mobile,East,Organic,VIP,0,4,2,3,0,37.0
2,60,150537.74250,19,35.004954,3.858211,25,Male,Electronics,Desktop,South,Organic,VIP,1,2,5,2,0,86.0
3,19,63508.76255,10,14.818000,7.554374,20,Male,Furniture,Desktop,West,Paid Ads,Premium,0,0,1,3,0,37.0
4,54,100399.55840,19,55.925462,0.197411,92,Male,Electronics,Mobile,South,Referral,Regular,1,4,1,2,0,86.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,56,113252.44120,16,26.327274,6.003410,135,Male,Kitchen,Mobile,South,Referral,Premium,1,0,1,2,0,67.0
499996,40,59758.01615,13,7.124139,-0.006796,123,Male,Kitchen,Desktop,North,Organic,Premium,1,1,3,3,0,52.0
499997,50,64968.69666,10,28.440505,0.649710,20,Male,Fashion,Mobile,North,Referral,VIP,0,4,2,2,0,37.0
499998,38,150832.32070,8,50.161579,2.903859,8,Female,Kitchen,Mobile,South,Organic,Premium,0,6,1,3,1,27.0
499999,75,103195.11530,4,23.528559,2.804215,168,Male,Groceries,Mobile,West,Paid Ads,VIP,0,5,1,4,0,13.0

In [6]:
dummies = pd.get_dummies(df['Gender'], dtype=int)
dummies

        Female  Male
0            0     1
1            1     0
2            0     1
3            0     1
4            0     1
...        ...   ...
499995       0     1
499996       0     1
499997       0     1
499998       1     0
499999       0     1

[500000 rows x 2 columns]

In [7]:
merged = pd.concat([df,dummies],axis='columns')
merged

,Age,AnnualIncome,NumberOfPurchases,TimeSpentOnWebsite,CustomerTenureYears,LastPurchaseDaysAgo,Gender,ProductCategory,PreferredDevice,Region,ReferralSource,CustomerSegment,LoyaltyProgram,DiscountsAvailed,SessionCount,CustomerSatisfaction,PurchaseStatus,SpendingScore,Female,Male
0,37,57722.57241,19,5.908826,1.093430,11,Male,Furniture,Desktop,South,Paid Ads,Regular,1,5,3,2,1,86.0,0,1
1,63,21328.92588,10,6.970749,0.649246,20,Female,Furniture,Mobile,East,Organic,VIP,0,4,2,3,0,37.0,1,0
2,60,150537.74250,19,35.004954,3.858211,25,Male,Electronics,Desktop,South,Organic,VIP,1,2,5,2,0,86.0,0,1
3,19,63508.76255,10,14.818000,7.554374,20,Male,Furniture,Desktop,West,Paid Ads,Premium,0,0,1,3,0,37.0,0,1
4,54,100399.55840,19,55.925462,0.197411,92,Male,Electronics,Mobile,South,Referral,Regular,1,4,1,2,0,86.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,56,113252.44120,16,26.327274,6.003410,135,Male,Kitchen,Mobile,South,Referral,Premium,1,0,1,2,0,67.0,0,1
499996,40,59758.01615,13,7.124139,-0.006796,123,Male,Kitchen,Desktop,North,Organic,Premium,1,1,3,3,0,52.0,0,1
499997,50,64968.69666,10,28.440505,0.649710,20,Male,Fashion,Mobile,North,Referral,VIP,0,4,2,2,0,37.0,0,1
499998,38,150832.32070,8,50.161579,2.903859,8,Female,Kitchen,Mobile,South,Organic,Premium,0,6,1,3,1,27.0,1,0
499999,75,103195.11530,4,23.528559,2.804215,168,Male,Groceries,Mobile,West,Paid Ads,VIP,0,5,1,4,0,13.0,0,1

In [8]:
df = merged.drop(['Gender','Female'],axis='columns')
df

,Age,AnnualIncome,NumberOfPurchases,TimeSpentOnWebsite,CustomerTenureYears,LastPurchaseDaysAgo,ProductCategory,PreferredDevice,Region,ReferralSource,CustomerSegment,LoyaltyProgram,DiscountsAvailed,SessionCount,CustomerSatisfaction,PurchaseStatus,SpendingScore,Male
0,37,57722.57241,19,5.908826,1.093430,11,Furniture,Desktop,South,Paid Ads,Regular,1,5,3,2,1,86.0,1
1,63,21328.92588,10,6.970749,0.649246,20,Furniture,Mobile,East,Organic,VIP,0,4,2,3,0,37.0,0
2,60,150537.74250,19,35.004954,3.858211,25,Electronics,Desktop,South,Organic,VIP,1,2,5,2,0,86.0,1
3,19,63508.76255,10,14.818000,7.554374,20,Furniture,Desktop,West,Paid Ads,Premium,0,0,1,3,0,37.0,1
4,54,100399.55840,19,55.925462,0.197411,92,Electronics,Mobile,South,Referral,Regular,1,4,1,2,0,86.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,56,113252.44120,16,26.327274,6.003410,135,Kitchen,Mobile,South,Referral,Premium,1,0,1,2,0,67.0,1
499996,40,59758.01615,13,7.124139,-0.006796,123,Kitchen,Desktop,North,Organic,Premium,1,1,3,3,0,52.0,1
499997,50,64968.69666,10,28.440505,0.649710,20,Fashion,Mobile,North,Referral,VIP,0,4,2,2,0,37.0,1
499998,38,150832.32070,8,50.161579,2.903859,8,Kitchen,Mobile,South,Organic,Premium,0,6,1,3,1,27.0,0
499999,75,103195.11530,4,23.528559,2.804215,168,Groceries,Mobile,West,Paid Ads,VIP,0,5,1,4,0,13.0,1

In [9]:
df.isnull().sum()

Age                     0
AnnualIncome            0
NumberOfPurchases       0
TimeSpentOnWebsite      0
CustomerTenureYears     0
LastPurchaseDaysAgo     0
ProductCategory         0
PreferredDevice         0
Region                  0
ReferralSource          0
CustomerSegment         0
LoyaltyProgram          0
DiscountsAvailed        0
SessionCount            0
CustomerSatisfaction    0
PurchaseStatus          0
SpendingScore           0
Male                    0
dtype: int64

In [10]:
features = ['Age','AnnualIncome','NumberOfPurchases',
            'TimeSpentOnWebsite','LastPurchaseDaysAgo','Male']

x = df[features]
y = df['SpendingScore']

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [11]:
print(x.columns)

Index(['Age', 'AnnualIncome', 'NumberOfPurchases', 'TimeSpentOnWebsite',
       'LastPurchaseDaysAgo', 'Male'],
      dtype='object')

In [12]:
len(x_train)

400000

In [13]:
len(x_test)

100000

In [14]:
len(y_test)

100000

In [15]:
x_train

array([[ 0.13050199, -1.01728798,  0.26895911, -1.44637709, -0.5136753 ,
        -1.00979295],
       [-0.31364671, -0.39902895, -1.56309383,  1.43314481,  0.05087745,
         0.99030202],
       [ 0.32085143, -0.64545864,  0.43550938, -0.38145796, -0.78684599,
        -1.00979295],
       ...,
       [ 0.76500013,  0.4097877 ,  0.76860992, -1.30187445,  0.37868227,
        -1.00979295],
       [ 0.51120087,  0.36069156,  1.10171045,  0.49575151, -0.73221185,
         0.99030202],
       [ 1.39949827,  0.49880753,  0.76860992,  0.82811251,  0.90681226,
        -1.00979295]])

In [16]:
x_test

array([[-0.25019689, -0.62592974, -0.73034249, -0.63933647,  1.61705604,
        -1.00979295],
       [-1.32884373,  0.30575665, -0.06414142, -0.97870194, -0.76863461,
        -1.00979295],
       [ 1.39949827, -1.21112661, -1.06344303,  0.6099888 , -0.73221185,
        -1.00979295],
       ...,
       [ 0.76500013, -1.02045854,  1.10171045,  1.58612282, -0.47725254,
        -1.00979295],
       [ 1.5263979 ,  0.75289576, -0.39724196,  0.15071167, -1.06001667,
         0.99030202],
       [-1.2019441 ,  0.96904721, -0.06414142,  1.27805702, -1.16928494,
        -1.00979295]])

In [17]:
y_train

269056    52.0
499174     5.0
85143     57.0
260335    75.0
338124    19.0
          ...
259178    86.0
365838    37.0
131932    67.0
146867    80.0
121958    67.0
Name: SpendingScore, Length: 400000, dtype: float64

In [18]:
y_test

104241    22.0
199676    41.0
140199    16.0
132814    33.0
408697    90.0
          ...
66361     57.0
497228    94.0
152728    80.0
50155     33.0
240408    41.0
Name: SpendingScore, Length: 100000, dtype: float64

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

model = LinearRegression()

model.fit(x_train, y_train)

#joblib.dump(sgd, r"C:/Users/srivi/Downloads/linear_model.pkl")
# print("Model saved successfully")

loaded_model = joblib.load(
    r"C:/Users/srivi/Downloads/linear_model.pkl"
)

y_pred = loaded_model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MSE :", mse)
print("RMSE:", rmse)
print("R2  :", r2)

D:\anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:35: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps,
D:\anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:597: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
D:\anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:836: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
D:\anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:862: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, positive=False):
D:\anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:1074: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=1, eps=np.finfo(np.float).eps,
D:\anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:1306: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=1, eps=np.finfo(np.float).eps,
D:\anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:1442: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, positive=False):

MSE : 11.256731513821284
RMSE: 3.3551052910186416
R2  : 0.9860363811140099

D:\anaconda\lib\site-packages\sklearn\linear_model\randomized_l1.py:152: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  precompute=False, eps=np.finfo(np.float).eps,
D:\anaconda\lib\site-packages\sklearn\linear_model\randomized_l1.py:318: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, random_state=None,
D:\anaconda\lib\site-packages\sklearn\linear_model\randomized_l1.py:575: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=4 * np.finfo(np.float).eps, n_jobs=1,

In [21]:
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

# Split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Create scaler
scaler = StandardScaler()

# Fit scaler ONLY on training data
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Train model
model = LinearRegression()
model.fit(x_train_scaled, y_train)

# Save both model and scaler
joblib.dump(model, "linear_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Model and scaler saved successfully!")

Model and scaler saved successfully!

In [22]:
import joblib
import numpy as np

# Load saved files
model = joblib.load("linear_model.pkl")
scaler = joblib.load("scaler.pkl")

# New customer data (same order as training)
# ['Age','AnnualIncome','NumberOfPurchases',
#  'TimeSpentOnWebsite','LastPurchaseDaysAgo','Male']

new_data = np.array([[30, 60000, 15, 35, 5, 1]])

# Scale using saved scaler (IMPORTANT)
new_data_scaled = scaler.transform(new_data)

# Predict
prediction = model.predict(new_data_scaled)

print("Predicted Spending Score:", prediction[0])

Predicted Spending Score: 63.24506374645507

D:\anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [20]:
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

sgd = SGDRegressor(
    max_iter=1000,
    learning_rate='constant',
    eta0=0.01,
    random_state=42
)

sgd.fit(x_train, y_train)

# joblib.dump(sgd, r"C:/Users/srivi/Downloads/sgd_model.pkl")
# print("Model saved successfully")

loaded_model = joblib.load(
    r"C:/Users/srivi/Downloads/sgd_model.pkl"
)
print("Model loaded successfully")

y_pred = loaded_model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MSE  :", mse)
print("RMSE :", rmse)
print("R2   :", r2)

Model loaded successfully
MSE  : 11.444647232162213
RMSE : 3.382993826799306
R2   : 0.9858032776176373

Linear Regression and Gradient Descent (SGDRegressor) were applied to predict customer Spending Score. Both models achieved similar performance with RMSE ≈ 3.3 and R² ≈ 0.986, indicating that the model explains 98% of the variance. This confirms successful convergence of gradient descent and strong linear relationships in the dataset.

In [23]:
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDRegressor

# Split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Create scaler
scaler = StandardScaler()

# Fit scaler ONLY on training data
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Train model
model = SGDRegressor()
model.fit(x_train_scaled, y_train)

# Save both model and scaler
joblib.dump(model, "sgd_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Model and scaler saved successfully!")

D:\anaconda\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)

Model and scaler saved successfully!

In [24]:
import joblib
import numpy as np

# Load saved files
model = joblib.load("sgd_model.pkl")
scaler = joblib.load("scaler.pkl")

# New customer data (same order as training)
# ['Age','AnnualIncome','NumberOfPurchases',
#  'TimeSpentOnWebsite','LastPurchaseDaysAgo','Male']

new_data = np.array([[30, 60000, 15, 35, 5, 1]])

# Scale using saved scaler (IMPORTANT)
new_data_scaled = scaler.transform(new_data)

# Predict
prediction = model.predict(new_data_scaled)

print("Predicted Spending Score:", prediction[0])

Predicted Spending Score: 63.34778230285623

D:\anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)